homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 408
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include_dir_merge_named customize
  customize_domain: {}
  customize_glob: {}

frontend:
http:
updater:
sun:
config:
# python_scripts:

history:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.living_temp_updated
      - binary_sensor.pir_livingroom
      - sensor.tv_mode
      - sensor.clientraw_wind_direction
      - persistent_notification.invalid_config
    domains:
      - automation
      - group
      - updater
      - script

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.living_temp_updated
      - sensor.ram_use
      - sensor.cpu_use
      - automation.in_temp_changed
      - binary_sensor.pir_livingroom
      - sensor.clientraw_wind_direction
      - binary_sensor.octoprint
      - media_player.spotify
    domains:
      - sun
      - updater
      - octoprint

logger:
 default: warning
 #logs:
    # homeassistant.components.mysensors: debug
    # mysensors.mysensors: debug
    # homeassistant.components.rflink: debug
    # custom_components.sensor.clientraw: info
    # homeassistant.components.device_tracker: debug

zone cottage:
  name: Chalupa
  latitude: !secret latitude_cottage
  longitude: !secret longitude_cottage
  radius: 200
  icon: mdi:home

#################################
###       COMPONENTS          ###
#################################

media_player:
  - platform: kodi
    host: 192.168.1.105
    turn_off_action: shutdown
  - platform: lg_netcast
    host: 192.168.1.106
    access_token: !secret tv_token
  - platform: spotify
    client_id:  !secret spotify_client
    client_secret: !secret spotify_secret

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 600
  # - platform: tplink
  #   host: 192.168.1.1
  #   username: !secret router_username
  #   password: !secret router_password
  - platform: mqtt
    devices:
      pokoj_pc: room/pc

lirc:

influxdb:
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.myslipo_1_0
      - sensor.myslipo_2_0
      - sensor.myslipo_3_0
      - sensor.clientraw_temperature_c
      - sensor.clientraw_feels_like_temp_c
      - sensor.clientraw_pressure
      - sensor.clientraw_daily_rain
      - sensor.kitchen_temp_batteries
      - sensor.living_temp_batteries
      - sensor.bedroom_temp_batteries
      - sensor.palm_moisture
      - sensor.palm_conductivity
      - sensor.palm_light_intensity


mysensors:
  gateways:
    - device: '192.168.1.113'
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      tcp_port: 5003
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api

rflink:
  port: /dev/serial0

octoprint:
  host: '192.168.1.115'
  api_key: !secret octoprint_api


light: !include_dir_merge_list lights
automation: !include automations.yaml
group: !include_dir_merge_named group
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell
switch: !include_dir_merge_list switch
# input_select: !include inputs/input_select.yaml
input_slider: !include_dir_merge_named input_slider

input_boolean: !include_dir_merge_named input_boolean
binary_sensor: !include_dir_merge_list binary_sensor
