homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 387
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include_dir_merge_list customize

frontend:
http:
updater:
conversation:
sun:

history:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.living_temp_updated
      - binary_sensor.pir_livingroom
      - sensor.tv_mode
      - sensor.clientraw_wind_direction
    domains:
      - automation
      - group
      - updater

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.living_temp_updated
      - sensor.ram_use
      - sensor.cpu_use
      - automation.in_temp_changed
      - binary_sensor.pir_livingroom
    domains:
      - sun
      - updater

logger:
 default: warning
 logs:
    # homeassistant.components.mysensors: debug
    # mysensors.mysensors: debug
    # homeassistant.components.rflink: debug
    custom_components.sensor.clientraw: info

zone cottage:
  name: Chalupa
  latitude: !secret latitude_cottage
  longitude: !secret longitude_cottage
  radius: 200
  icon: mdi:home

# Text to speech
tts:
  platform: google
  cache: true
  cache_dir: /home/homeassistant/.homeassistant/tts
  time_memory: 300

#################################
###       COMPONENTS          ###
#################################

media_player kodi:
  - platform: kodi
    host: 192.168.1.105
    turn_off_action: shutdown

media_player tv:
  - platform: lg_netcast
    host: 192.168.1.106
    access_token: !secret tv_token

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 10

# lircy:
#   path: '/home/homeassistant/.homeassistant/.lircrc'

lirc:

influxdb:
  username: !secret influxdb_username
  password: !secret influxdb_password
  whitelist:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.ram_use
    - sensor.cpu_use
    - sensor.myslipo_1_0
    - sensor.myslipo_2_0
    - sensor.myslipo_3_0
    - sensor.clientraw_temperature_c
    - sensor.clientraw_feels_like_temp_c
    - sensor.clientraw_pressure
    - sensor.clientraw_daily_rain
    - sensor.kitchen_temp_batteries
    - sensor.living_temp_batteries
    - sensor.bedroom_temp_batteries
    - sensor.palm_moisture
    - sensor.palm_conductivity
    - sensor.palm_light_intensity


mysensors:
  gateways:
    - device: mqtt
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      topic_in_prefix: 'mysensors-out'
      topic_out_prefix: 'mysensors-in'
  debug: true
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: pushetta
    platform: pushetta
    api_key: !secret pushetta_api
    channel_name: !secret pushetta_channel

rflink:
  port: /dev/serial0
  wait_for_ack: true

light: !include_dir_merge_list lights
automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
#script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell
#input_select: !include inputs/input_select.yaml
#input_slider: !include inputs/input_slider.yaml

binary_sensor: !include_dir_merge_list binary_sensor
