homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 408
  unit_system: metric
  time_zone: Europe/Prague
  customize: !include customize.yaml
  packages: !include_dir_named components/

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html

http:
updater:
  include_used_components: true

sun:
config:
# python_scripts:

automation: !include automations.yaml
script: !include scripts.yaml
group: !include_dir_merge_named groups/

mqtt:
  broker: localhost
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 600

lirc:
