################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.bedroom:
      order: 3

################################################################
# GROUPS
################################################################

group:
  bedroom:
    view: yes
    name: Ložnice
    entities:
      - group.bedroom_lights
      - sensor.myslipo_2_0
      - device_tracker.bedroom_pc
      - media_player.spotify
      - device_tracker.octoprint
      - group.octoprint

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################