################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.bedroom:
      order: 3

################################################################
# GROUPS
################################################################

group:
  bedroom:
    view: yes
    name: Ložnice
    entities:
      - group.bedroom_lights
      - group.bedroom_pc
      - sensor.myslipo_2_0
      - device_tracker.bedroom_pc
      - media_player.spotify
      - device_tracker.octoprint
      - device_tracker.bedroom_pc_mqtt
      - group.octoprint
  bedroom_pc:
    name: Ovládaní
    entities:
      - switch.socket_table
      - script.bedroom_pc_off


################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################