################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.hall:
      order: 6
      
################################################################
# GROUPS
################################################################

group:
  hall:
    view: yes
    name: Chodba
    entities:
      - group.hall_lights

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################