################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.kitchen:
      order: 4

################################################################
# GROUPS
################################################################

group:
  kitchen:
    view: yes
    name: Kuchyně
    entities:
      - group.kitchen_lights
      - sensor.myslipo_3_0

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################