################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.livingroom:
      order: 2
      
################################################################
# GROUPS
################################################################

group:    
  livingroom:
    view: yes
    name: Obývák
    entities:
      - binary_sensor.pir_livingroom
      - sensor.av_state
      - sensor.tv_mode
      - group.livingroom_lights
      - group.palm_moisture
      - sensor.myslipo_1_0
      - media_player.lg_tv_remote
      - media_player.kodi

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################

