################################################################
# COMPONENTS
################################################################

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    group.room:
      order: 5

################################################################
# GROUPS
################################################################

group:
  room:
    view: yes
    name: Pokoj
    entities:
      - group.room_lights


################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################
