switch:
  - platform: mqtt
    name: "lazygardener_herbs"
    command_topic: "LazyGardener/relay0"
    state_topic: "LazyGardener/relay0/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_fruit"
    command_topic: "LazyGardener/relay1"
    state_topic: "LazyGardener/relay1/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_flowers"
    command_topic: "LazyGardener/relay2"
    state_topic: "LazyGardener/relay2/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_veg"
    command_topic: "LazyGardener/relay3"
    state_topic: "LazyGardener/relay3/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_shade_flowers"
    command_topic: "LazyGardener/relay4"
    state_topic: "LazyGardener/relay4/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: template
    switches:
      lazygardener_herbs_template:
        friendly_name: 'Bylinky + papriky'
        value_template: "{{ is_state('switch.lazygardener_herbs', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_herbs
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_herbs
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_herbs

      lazygardener_fruit_template:
        friendly_name: 'Ovoce'
        value_template: "{{ is_state('switch.lazygardener_fruit', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_fruit
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_fruit
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_fruit

      lazygardener_flowers_template:
        friendly_name: 'Kytičky + jahody'
        value_template: "{{ is_state('switch.lazygardener_flowers', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_flowers
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_flowers
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_flowers

      lazygardener_veg_template:
        friendly_name: 'Zelenina'
        value_template: "{{ is_state('switch.lazygardener_veg', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_veg
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_veg
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_veg

      lazygardener_shade_flowers_template:
        friendly_name: 'Záhon u plotu'
        value_template: "{{ is_state('switch.lazygardener_shade_flowers', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_shade_flowers
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_shade_flowers
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_shade_flowers

      lazygardener_all:
        friendly_name: "Zalít vše"
        value_template: "{{ is_state('script.lazygardener_all', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_all
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_all
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: mqtt.publish
            data:
              topic: "lazygardener/off"
              qos: 1
              retain: false

sensor:
  - platform: template
    sensors:
      lazygardener_watering:
        friendly_name: "Stav zalévání"
        value_template: "{% if is_state('input_boolean.lazygardener_watering', 'on') %}Zalévá se{% else %}Vypnuto{% endif %}"
      
input_boolean:
  lazygardener_watering:
    initial: off

input_slider:
  lazygardener_herbs_duration:
    name: "Doba trvání"
    initial: 5
    min: 2
    max: 9
    step: 1

  lazygardener_fruit_duration:
    name: "Doba trvání"
    initial: 7
    min: 1
    max: 9
    step: 1

  lazygardener_flowers_duration:
    name: "Doba trvání"
    initial: 6
    min: 1
    max: 9
    step: 1

  lazygardener_veg_duration:
    name: "Doba trvání"
    initial: 5
    min: 1
    max: 9
    step: 1

  lazygardener_shade_flowers_duration:
    name: "Doba trvání"
    initial: 6
    min: 1
    max: 9
    step: 1