- platform: template
  sensors:
    tv_mode:
      value_template: >
        {% if is_state('sensor.tv_mode', 'kodi') %}
          kodi
        {% elif is_state('sensor.tv_mode', 'bt') %}
          bt
        {% else %}
          tv
        {% endif %}
    av_state:
      value_template: >
        {% if is_state('sensor.av_state', 'off') %}
          off
        {% else %}
          on
        {% endif %}