- alias: IR TV power toggle
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_POWER2
  action:
    - service: shell_command.tv_toggle

- alias: IR AV state toggle
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_POWER
  action:
    - service_template: >
        {% if states.sensor.av_state.state == 'on' %}
          shell_command.av_state_off
        {% else %}
          shell_command.av_state_on
        {% endif %}

- alias: IR TV channel up
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_CHANNELUP
  action:
    service: shell_command.tv_channel_up

- alias: IR TV channel down
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_CHANNELDOWN
  action:
    service: shell_command.tv_channel_down

- alias: IR TV left
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_LEFT
  action:
    service_template: >
      {% if is_state('sensor.tv_mode', 'kodi') %}
        {{ shell_command.kodi_left }}
      {% else %}
        {{ shell_command.tv_left }}
      {% endif %}

- alias: IR TV right
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_RIGHT
  action:
    service_template: >
      {% if is_state('sensor.tv_mode', 'kodi') %}
        {{ shell_command.kodi_right }}
      {% else %}
        {{ shell_command.tv_right }}
      {% endif %}

- alias: IR TV up
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_UP
  action:
    service_template: >
      {% if is_state('sensor.tv_mode', 'kodi') %}
        {{ shell_command.kodi_up }}
      {% else %}
        {{ shell_command.tv_up }}
      {% endif %}

- alias: IR TV down
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_DOWN
  action:
    service_template: >
      {% if is_state('sensor.tv_mode', 'kodi') %}
        {{ shell_command.kodi_down }}
      {% else %}
        {{ shell_command.tv_down }}
      {% endif %}

- alias: IR TV ok
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_ENTER
  action:
    service_template: >
      {% if is_state('sensor.tv_mode', 'kodi') %}
        {{ shell_command.kodi_ok }}
      {% else %}
        {{ shell_command.tv_ok }}
      {% endif %}

- alias: IR TV DVD
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_DVD
  action:
    - service: shell_command.tv_input_kodi
    - service: shell_command.tv_mode_kodi

- alias: IR TV mode bt
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_SAT
  action:
    service: shell_command.tv_mode_bt

- alias: IR TV
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_TV
  action:
    - service: shell_command.tv_input_tv
    - service: shell_command.tv_mode_tv

- alias: IR TV red
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_CHANNEL
  action:
    service: shell_command.tv_red

- alias: IR TV back
  trigger:
    platform: event
    event_type: ir_command_received
    event_data:
      button_name: AV_KEY_BACK
  action:
    service: shell_command.kodi_back
