- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data_template: 
        message: "Home Assistant {{ states.updater.updater.state }} k dispozici"
    - service: notify.pushetta
      data_template: 
        message: "Home Assistant {{ states.updater.updater.state }} k dispozici"


- alias: Disk Use Alarm
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 80
  action:
    - service: persistent_notification.create
      data:
        message: 'Dochází místo na disku HA: {{ states.sensor.disk_use_.state }}%!'
        title: "POZOR!!"
    - service: notify.pushbullet
      data_template:
        message: 'Dochází místo na disku HA: {{ states.sensor.disk_use_.state }}%!'