################################################################
# COMPONENTS
################################################################
switch:
  - platform: command_line
    switches:
      internet_nexus5:
        command_on: "/home/homeassistant/.homeassistant/includes/control_internet.sh bc:f5:ac:fe:e9:8a on"
        command_off: "/home/homeassistant/.homeassistant/includes/control_internet.sh bc:f5:ac:fe:e9:8a off"
        friendly_name: "NEXUS 5: zakázat internet"

      # internet_ipad2:
      #   command_on: "/home/homeassistant/.homeassistant/includes/control_internet.sh DE:VI:CE:TWO:MAC on"
      #   command_off: "/home/homeassistant/.homeassistant/includes/control_internet.sh DE:VI:CE:TWO:MAC off"
      #   friendly_name: Disconnect iPad 2 (manual)

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    switch.internet_nexus5:
      assumed_state: false
      icon: "mdi:cellphone-android"

################################################################
# GROUPS
################################################################

group:
  control_internet:
    name: Internet
    entities:
      - switch.internet_nexus5

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################