################################################################
# COMPONENTS
################################################################

switch:
  - platform: mqtt
    name: "lazygardener_herbs"
    command_topic: "lazygardener/relay0"
    state_topic: "lazygardener/relay0/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_fruit"
    command_topic: "lazygardener/relay1"
    state_topic: "lazygardener/relay1/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_flowers"
    command_topic: "lazygardener/relay2"
    state_topic: "lazygardener/relay2/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_veg"
    command_topic: "lazygardener/relay3"
    state_topic: "lazygardener/relay3/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: mqtt
    name: "lazygardener_shade_flowers"
    command_topic: "lazygardener/relay4"
    state_topic: "lazygardener/relay4/state"
    payload_on: 'ON'
    payload_off: 'OFF'
    optimistic: false
    qos: 1

  - platform: template
    switches:
      lazygardener_herbs_template:
        friendly_name: 'Bylinky + papriky'
        value_template: "{{ is_state('switch.lazygardener_herbs', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_herbs
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_herbs
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_herbs

      lazygardener_fruit_template:
        friendly_name: 'Ovoce'
        value_template: "{{ is_state('switch.lazygardener_fruit', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_fruit
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_fruit
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_fruit

      lazygardener_flowers_template:
        friendly_name: 'Kytičky + jahody'
        value_template: "{{ is_state('switch.lazygardener_flowers', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_flowers
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_flowers
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_flowers

      lazygardener_veg_template:
        friendly_name: 'Zelenina'
        value_template: "{{ is_state('switch.lazygardener_veg', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_veg
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_veg
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_veg

      lazygardener_shade_flowers_template:
        friendly_name: 'Záhon u plotu'
        value_template: "{{ is_state('switch.lazygardener_shade_flowers', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_shade_flowers
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_shade_flowers
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: switch.turn_off
            entity_id: switch.lazygardener_shade_flowers

      lazygardener_all:
        friendly_name: "Zalít vše"
        value_template: "{{ is_state('script.lazygardener_all', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.lazygardener_all
        turn_off:
          - service: script.turn_off
            entity_id: script.lazygardener_all
          - service: input_boolean.turn_off
            entity_id: input_boolean.lazygardener_watering
          - service: mqtt.publish
            data:
              topic: "lazygardener/off"
              qos: 1
              retain: false

sensor:
  - platform: template
    sensors:
      lazygardener_watering:
        friendly_name: "Stav zalévání"
        value_template: "{% if is_state('input_boolean.lazygardener_watering', 'on') %}Zalévá se{% else %}Vypnuto{% endif %}"
      
input_boolean:
  lazygardener_watering:
    initial: off

input_slider:
  lazygardener_herbs_duration:
    name: "Doba trvání"
    initial: 5
    min: 2
    max: 9
    step: 1

  lazygardener_fruit_duration:
    name: "Doba trvání"
    initial: 7
    min: 1
    max: 9
    step: 1

  lazygardener_flowers_duration:
    name: "Doba trvání"
    initial: 6
    min: 1
    max: 9
    step: 1

  lazygardener_veg_duration:
    name: "Doba trvání"
    initial: 5
    min: 1
    max: 9
    step: 1

  lazygardener_shade_flowers_duration:
    name: "Doba trvání"
    initial: 6
    min: 1
    max: 9
    step: 1

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    switch.lazygardener_herbs_template:
      custom_ui_state_card: custom-ui
      show_last_changed: true
      icon: mdi:leaf

    switch.lazygardener_fruit_template:
      custom_ui_state_card: custom-ui
      show_last_changed: true
      icon: mdi:food-apple

    switch.lazygardener_flowers_template:
      custom_ui_state_card: custom-ui
      show_last_changed: true
      icon: mdi:flower

    switch.lazygardener_veg_template:
      custom_ui_state_card: custom-ui
      show_last_changed: true
      icon: mdi:carrot

    switch.lazygardener_shade_flowers_template:
      custom_ui_state_card: custom-ui
      show_last_changed: true
      icon: mdi:gate

    switch.lazygardener_all:
      icon: mdi:water-pump

    input_slider.lazygardener_herbs_duration:
      icon: mdi:timer

    input_slider.lazygardener_fruit_duration:
      icon: mdi:timer

    input_slider.lazygardener_flowers_duration:
      icon: mdi:timer

    input_slider.lazygardener_veg_duration:
      icon: mdi:timer

    input_slider.lazygardener_shade_flowers_duration:
      icon: mdi:timer

    group.lazygardener:
      order: 1



################################################################
# GROUPS
################################################################

group:
  lazygardener:
    view: true
    name: "lazy-gardener"
    entities:
      - group.lazygardener_control
      - group.lazygardener_herbs
      - group.lazygardener_fruit
      - group.lazygardener_flowers
      - group.lazygardener_veg
      - group.lazygardener_shade_flowers

  lazygardener_control:
    name: "Ovládání"
    entities:
      - switch.lazygardener_all
      - sensor.lazygardener_watering

  lazygardener_herbs:
    name: "Bylinky + papriky"
    entities:
      - switch.lazygardener_herbs_template
      - input_slider.lazygardener_herbs_duration

  lazygardener_fruit:
    name: "Ovoce"
    entities:
      - switch.lazygardener_fruit_template
      - input_slider.lazygardener_fruit_duration

  lazygardener_flowers:
    name: "Kytičky + jahody"
    entities:
      - switch.lazygardener_flowers_template
      - input_slider.lazygardener_flowers_duration

  lazygardener_veg:
    name: "Zelenina"
    entities:
      - switch.lazygardener_veg_template
      - input_slider.lazygardener_veg_duration

  lazygardener_shade_flowers:
    name: "Záhon u plotu"
    entities:
      - switch.lazygardener_shade_flowers_template
      - input_slider.lazygardener_shade_flowers_duration

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################

script:
  lazygardener_all:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_herbs

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering

      - delay: '00:{{ (states.input_slider.lazygardener_herbs_duration.state | int ) -1}}:00'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_fruit
      - delay: '00:{{ states.input_slider.lazygardener_fruit_duration.state | int }}:00'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_flowers
      - delay: '00:{{ states.input_slider.lazygardener_flowers_duration.state | int }}:00'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_veg
      - delay: '00:{{ states.input_slider.lazygardener_veg_duration.state | int }}:00'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_herbs
      - delay: '00:01:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_herbs

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering

  lazygardener_herbs:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_herbs

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering

      - delay: '00:{{ states.input_slider.lazygardener_herbs_duration.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_herbs

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering

  lazygardener_fruit:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_fruit

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering

      - delay: '00:{{ states.input_slider.lazygardener_fruit_duration.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_fruit

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering

  lazygardener_flowers:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_flowers

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering

      - delay: '00:{{ states.input_slider.lazygardener_flowers_duration.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_flowers

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering

  lazygardener_veg:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_veg

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering

      - delay: '00:{{ states.input_slider.lazygardener_veg_duration.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_veg

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering

  lazygardener_shade_flowers:
    sequence:
      - condition: state
        entity_id: input_boolean.lazygardener_watering
        state: 'off'

      - service: switch.turn_on
        data:
          entity_id: switch.lazygardener_shade_flowers

      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.lazygardener_watering
          
      - delay: '00:{{ states.input_slider.lazygardener_shade_flowers_duration.state | int }}:00'
      - service: switch.turn_off
        data:
          entity_id: switch.lazygardener_shade_flowers

      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.lazygardener_watering
