################################################################
# COMPONENTS
################################################################

sensor:
  - platform: miflora
    mac: "C4:7C:8D:62:4D:4F"
    monitored_conditions:
      - moisture
      - conductivity
      - battery
      - light
    name: plant1

  - platform: template
    sensors:
      plant1_battery_template:
        value_template: >
          {% if states('sensor.plant1_battery') | int %}
            {{ states('sensor.plant1_battery') | float }}
          {% endif %}
        friendly_name: 'Kala baterie'
        unit_of_measurement: '%'
        icon_template: >
          {% if states('sensor.plant1_battery') | int %}
            {% set batt = states('sensor.plant1_battery') | float %}
            {% if batt > 95 %}
              mdi:battery
            {% elif batt > 85 %}
              mdi:battery-90
            {% elif batt > 75 %}
              mdi:battery-80
            {% elif batt > 65 %}
              mdi:battery-70
            {% elif batt > 55 %}
              mdi:battery-60
            {% elif batt > 45 %}
              mdi:battery-50
            {% elif batt > 35 %}
              mdi:battery-40
            {% elif batt > 25 %}
              mdi:battery-30
            {% elif batt > 15 %}
              mdi:battery-20
            {% elif batt > 10 %}
              mdi:battery-10
            {% else %}
              mdi:battery-outline
            {% endif %}
          {% else %}
            mdi:battery-unknown
          {% endif %}

plant:
  kala:
    sensors:
      moisture: sensor.plant1_moisture
      conductivity: sensor.plant1_conductivity
    min_moisture: 20
    min_conductivity: 300

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    sensor.plant1_moisture:
      friendly_name: 'Vlhost půdy'
      icon: mdi:water-percent

    sensor.plant1_conductivity:
      friendly_name: 'Hnojivo'
      icon: mdi:test-tube

    sensor.plant1_light_intensity:
      friendly_name: Světelné podmínky
      icon: mdi:white-balance-sunny

################################################################
# GROUPS
################################################################

group:
  plant1_moisture:
    name: Kala
    entities:  
      - plant.kala
      - sensor.plant1_moisture
      - sensor.plant1_conductivity
      - sensor.plant1_light_intensity

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################
