################################################################
# COMPONENTS
################################################################

mysensors:
  gateways:
    - device: '192.168.1.113'
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      tcp_port: 5003
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

sensor:
  - platform: mysensors

  - platform: attributes
    friendly_name: Baterie
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - sensor.myslipo_1_0
      - sensor.myslipo_2_0
      - sensor.myslipo_3_0
      - sensor.myslipo_4_0

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    sensor.myslipo_1_0:
      friendly_name: 'Obývák'

    sensor.myslipo_1_0_battery_level:
      friendly_name: 'Baterie obývák'

    sensor.myslipo_2_0:
      friendly_name: 'Ložnice'

    sensor.myslipo_3_0:
      friendly_name: 'Kuchyně'

    sensor.myslipo_4_0:
      friendly_name: 'Teplota za oknem'

################################################################
# GROUPS
################################################################

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################