################################################################
# COMPONENTS
################################################################

octoprint:
  host: '192.168.1.115'
  api_key: !secret octoprint_api

sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    sensor.octoprint_current_state:
      friendly_name: Status
      icon: mdi:printer-3d

    sensor.octoprint_actual_tool0_temp:
      friendly_name: Aktuální teplota trysky

    sensor.octoprint_target_tool0_temp:
      friendly_name: Požadovaná teplota trysky

    sensor.octoprint_actual_bed_temp:
      friendly_name: Aktuální teplota podložky

    sensor.octoprint_target_bed_temp:
      friendly_name: Požadovaná teplota podložky

    binary_sensor.octoprint_printing_error:
      friendly_name: Chyba tisku
      icon: mdi:alert-octagon

    automation.konec_3d_tisku:
      icon: mdi:printer-3d
      
    automation.chyba_3d_tisku:
      icon: mdi:printer-3d


################################################################
# GROUPS
################################################################

group:
  octoprint:
    name: OctoPrint
    entities:
      - sensor.octoprint_current_state
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_target_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_target_tool0_temp
      - binary_sensor.octoprint_printing_error

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################