################################################################
# COMPONENTS
################################################################

binary_sensor:
  - platform: rpi_gpio
    pull_mode: DOWN
    ports:
      27: PIR livingroom

################################################################
# CUSTOMIZE
################################################################

################################################################
# GROUPS
################################################################

################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################