################################################################
# COMPONENTS
################################################################

sensor:
  - platform: clientraw
    url: !secret clientraw_url
    interval: 12
    monitored_conditions:
      - dewpoint_c
      - temp_c
      - feels_like_c
      - wind_dir
      - wind_gust_kph
      - wind_kph
      - symbol
      - daily_rain
      - pressure
      - humidity

  - platform: systemmonitor
    resources:
    - type: since_last_boot
    - type: memory_use_percent
    - type: processor_use
    - type: disk_use_percent
      arg: "/"

  - platform: speedtest
    hour:
    - 8
    - 12
    - 16
    - 18
    - 20
    - 22
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: template
    sensors:
      since_last_boot_templated:
        friendly_name: 'Poslední restart'
        icon_template: mdi:restart
        value_template: >-
          {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
          {%- set count = slb | length -%}
          {%- set hms = slb[count - 1] -%}
          {%- set hms_trimmed = hms.split('.')[0] -%}
          {%- set hms_split = hms_trimmed.split(':') -%}
          {%- set day = slb[0] | int -%}
          {%- set hours = hms_split[0] | int -%}
          {%- set minutes = hms_split[1] | int -%}
          {%- set seconds = hms_split[2] | int -%}
          {%- if count == 3 -%}
            {%- if day == 1 -%}
              1 den {{ ' ' }}
            {%- elif day > 1 and day < 5 -%}
              {{ day }} dny {{ ' ' }}
            {%- else -%}
              {{ day }} dnů {{ ' ' }}
            {%- endif -%}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hodina
            {%- elif hours > 1 and hours < 5 -%}
              {{ hours }} hodiny
            {%- else -%}
              {{ hours }} hodin
            {%- endif -%}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {%- if minutes == 1 -%}
              1 minuta
            {%- elif minutes > 1 and minutes < 5 -%}
              {{ minutes }} minuty
            {%- else -%}
              {{ minutes }} minut
            {%- endif -%}
          {%- endif -%}
          {%- if seconds > 0 -%}
            {%- if hours > 0 or minutes > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {%- if seconds == 1 -%}
              1 sekunda
            {%- elif seconds > 1 and seconds < 5 -%}
              {{ seconds }} sekundy
            {%- else -%}
              {{ seconds }} sekund
            {%- endif -%}
          {%- endif -%}
################################################################
# CUSTOMIZE
################################################################

homeassistant:
  customize:
    script.restart:
      friendly_name: Restartovat systém
      icon: mdi:restart

    sensor.speedtest_ping:
      friendly_name: 'Ping'
      icon: mdi:clock-fast

    sensor.speedtest_download:
      friendly_name: 'Download'
      icon: mdi:download

    sensor.speedtest_upload:
      friendly_name: 'Upload'
      icon: mdi:upload

    sensor.ram_use:
      friendly_name: Využito paměti
      icon: mdi:memory

    sensor.cpu_use:
      friendly_name: Využití procesoru
      icon: mdi:matrix

    sensor.disk_use_:
      friendly_name: Využité místo
      icon: mdi:sd

################################################################
# GROUPS
################################################################

group:
  system:
    name: Systém
    entities:
      - sensor.since_last_boot_templated
      - sensor.ram_use
      - sensor.cpu_use
      - sensor.disk_use_
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
      
################################################################
# SCENES
################################################################

################################################################
# SCRIPTS
################################################################
script:
  restart:
    sequence:
      - service: homeassistant.restart